### PR TITLE
Quickstart guide

### PR DESCRIPTION
**Pull request by renanborgescampos**
This PR contains changes to allow nested attributes for our API requests using the "Sample Request" form. Also, there are some custom style changes for the Quickstart guide.

### CODE REVIEW

**Comment by danielnc** [comment]
@renanborgescampos did you tried pushing this nested attributes fixed to original project?

**Comment by renanborgescampos** [comment]
@danielnc no I didn't. To be honest I don't know if this is actually a fix or a customization to attend our needs.

I'm not sure if the idea of the original apidoc project is actually to send parameters like this: `{"resource.field": "value"}`, with fields separated by dots.
Since the original code make it impossible to create hashes for the nested attributes, my change was basically split the "." and create a hash, to send parameters like this: `{"resource": {"field": "value"}}`. That will work for our API,  since all of our endpoints are expecting hashes for nested attributes. 

I know there are some people complaining that they would like to send hashes attributes (https://github.com/apidoc/apidoc/issues/380 , https://github.com/apidoc/apidoc/issues/533), but at the same time I don't think its possible to do that and keep compability with the old behavior. 

Also, this fix is a change on a javascript file inside "template" folder thus its not part of the apidocjs core logic. I believe they did that so people could customize this js according to their needs just like we did.

What you think? You think I still should send it to original project and warn about the modified behavior?

**Comment by danielnc** [comment]
@renanborgescampos lets make sure we push this improvement to the original project as our contribution 😄 

maybe adding it as an option you can pick: hash or dot


I would talk to the maintainers but personally I like to contribute back to projects we use 💃

**Comment by renanborgescampos** [comment]
@danielnc Sure, I'll check the code to see what I can do to add it as an option and push this improvement to the origial project.

@zzzcm Review please

**Review by ghost — APPROVED** [review]

**Comment by renanborgescampos** [comment]
QA results are here: https://github.com/CareMessagePlatform/CareMessage/pull/1280#pullrequestreview-15541254

**Pull request merged**
